trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:

- checkout: self

# Install UiPath CLI
- task: UiPathInstallPlatform@4
  displayName: Install UiPath Platform

# Pack the automation
- task: UiPathPack@4
  displayName: Pack UiPath Project
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: 'project.json'
    outputType: 'Process'

# Deploy package to Orchestrator
- task: UiPathDeploy@4
  displayName: Deploy Package
  inputs:
    orchestratorConnection: 'UiPath-Orchestrator'
    packagesPath: '$(Build.ArtifactStagingDirectory)'
    folderName: 'Shared'